name: publish release to s3

on:
  workflow_dispatch:
    inputs:
      artifactUrl:
        description: 'URL of artifact to upload'
        required: true
      moveToOldReleases:
        description: 'Whether or not to move current release to old releases'
        required: true
        default: 'true'

jobs:
  testMove:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.moveToOldReleases == 'true' }}
    steps:
      - run: echo "gonna move move move"
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Gonna upload from: ${{ github.event.inputs.artifactUrl }}"
          wget ${{ github.event.inputs.artifactUrl }}
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
