name: publish release to s3

on:
  workflow_dispatch:
    inputs:
      artifactUrl:
        description: 'URL of artifact to upload'
        required: true

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Gonna upload from: ${{ github.event.inputs.artifactUrl }}"
          echo "and done"
