name: publish release to s3

on:
  workflow_dispatch:
    inputs:
      artifactUrl:
        description: 'URL of artifact to upload'
        required: true
      moveToOldReleases:
        description: 'Whether or not to move current release to old releases'
        required: true
        default: 'true'

jobs:
  testJob:
    env:
      AWS_S3_BUCKET: compliance-builds
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
      - name: move old files
        if: ${{ github.event.inputs.moveToOldReleases == 'true' }}
        run: |
          file=`aws s3 ls "$AWS_S3_BUCKET" | grep -v "older" | cut -d ' ' -f 5-`
          aws s3 cp --acl public-read "s3://$AWS_S3_BUCKET/$file" "s3://$AWS_S3_BUCKET/older versions/$file"
          #aws s3 rm "s3://$AWS_S3_BUCKET/$file"
      - run: |
          wget ${{ github.event.inputs.artifactUrl }}
          file=`ls`
          aws s3 cp --acl public-read "$file" "s3://$AWS_S3_BUCKET/$file"
