name: publish release to s3

on:
  workflow_dispatch:
    inputs:
      artifactUrl:
        description: 'URL of artifact to upload'
        required: true
      moveToOldReleases:
        description: 'Whether or not to move current release to old releases'
        required: true
        default: 'true'

jobs:
  testMove:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.moveToOldReleases == 'true' }}
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
      - run: |
          file=`aws s3 ls "$AWS_S3_BUCKET" | grep -v "older" | cut -d ' ' -f 5-`
          echo "gonna run aws s3 cp s3://$AWS_S3_BUCKET/$file 's3://$AWS_S3_BUCKET/older versions/$file'"
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
      - run: |
          echo "Gonna upload from: ${{ github.event.inputs.artifactUrl }}"
          wget ${{ github.event.inputs.artifactUrl }}
          file=`ls`
          echo "Gonna upload $file to s3://$AWS_S3_BUCKET/$file"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
